### ISSUE TITLE
Refactor ColumnStatistics, add hasMinimum/Maximum/Sum/..., toString methods

### ISSUE THREAD

**Issue by asandryh** [hortonworks/orc#117]

**Comment by omalley** [comment]
I'm half way through this because you left the build broken.

**Comment by asandryh** [comment]
Sorry about this. I pushed a bunch of changes yesterday and thought I resolved all issues. Will be more careful in the future.

I can work on this today, too. Let me know what I can do.




On 02/14/2015 10:34 AM, omalley wrote:

I'm half way through this because you left the build broken.

�

**Comment by omalley** [comment]
I didn't implement toString, which would be a good thing. Please file a new issue.

**Comment by jxu1989** [comment]
I should be more careful, sorry and thanks Owen.
