### ISSUE TITLE
Implement toString() methods for ColumnStatistics

### ISSUE THREAD

**Issue by asandryh** [hortonworks/orc#118]

**Comment by jxu1989** [comment]
fixed by adding toString() to column statistics

**Comment by asandryh** [comment]
Min, max, and sum may not be defined. Please 
1) add the following public virtual methods to appropriate ColumnStatistics subclasses: hasMinimum(), hasMaximum(), hasSum();
2) implement these methods for each ColumnStatistics sub-subclass (ending with Impl);
3) in each toString() method, check whether min/max/sum exists; if does not, print "NOT DEFINED";

**Comment by swalkaus** [comment]
From code inspection it looks like some, perhaps all of this, is done.
