### ISSUE TITLE
fix memory issues with StripeStatisticsImpl

### ISSUE THREAD

**Issue by omalley** [hortonworks/orc#128]
The memory from StripeStatisticsImpl is not being freed properly.

**Comment by omalley** [comment]
This patch fixes the fundamental problem, which was that StripeStatisticsImpl was returning parts of its internal data using a unique_ptr and failing to do so in its own destructor. I also abstracted the file and stripe statistics into a single Statistics class.

Other changes:
* fixed lines that were too long
* removed +1 offsets that were skipping over the root column
* removed the need for the type when building statistics
* added private copy constructor and assignment operator for StatisticsImpl
* updated the valgrind suppression file

Valgrind is now clean. :)

**Comment by jxu1989** [comment]
Out of curiosity, if we plan to use statistics to compare with the predicate, what is the root column statistics used for?
If I understood right before, the actual column statistics start from 1?

On 02/25/2015 01:33 AM, omalley wrote:

This patch fixes the fundamental problem, which was that StripeStatisticsImpl was returning parts of its internal data using a unique_ptr and failing to do so in its own destructor. I also abstracted the file and stripe statistics into a single Statistics class.

Other changes:

  *   fixed lines that were too long
  *   removed +1 offsets that were skipping over the root column
  *   removed the need for the type when building statistics
  *   added private copy constructor and assignment operator for StatisticsImpl
  *   updated the valgrind suppression file

Valgrind is now clean. :)

�
Reply to this email directly or view it on GitHub<https://github.com/hortonworks/orc/issues/128#issuecomment-75881935>.



--
Jing Xu
Software Engineer
Vertica, an HP Company
jing.xu2@hp.com<mailto:jing.xu2@hp.com>

**Comment by omalley** [comment]
Ok, the problem is that the columns are a tree and not a list. In particular if your row looks like:
```
struct<
   col1: map<int, int>,
   col2: string>
```
The root is column 0, "col1" is column 1(map), 2(key), and 3(value), and "col2" is column 4. So offsetting by 1 to skip over the root will work in the easy cases, but won't really work in the general case.
