### ISSUE TITLE
pass examples dir as a cmake parameter

### ISSUE THREAD

**Issue by thanhdowisc** [hortonworks/orc#133]
TestDriver currently assumes it can by default find examples dir in its parent folder. This is not true at least for Windows.

A cleaner and cross-platform solution would be adding a cmake input for this value in config.hh.in

**Comment by omalley** [comment]
Why should the builder change where the example directory is? It is always in ${CMAKE_SOURCE_DIR}/examples. I find using a relative path better as a runtime default, but I guess an absolute path will be ok.

**Comment by thanhdowisc** [comment]
The current design works fine when we run all the test at once after building (make test in posix, or ctest in windows) because for this test target, we pass the example folder as a second parameter.

However, if we want to run each test separately (e.g., for debugging), there will be some issues:
1. The test program assumes 2 argument only, so we can not run something like 

test-orc --gtest_filter=RLE*

or even

test-orc {PathToExamplesDir} --gtest_filter=RLE*

2. I am not sure about posix, but in Windows, the test-orc.exe by default is not located under {CMAKE_SOURCE_DIR}/build (of course, we could change the CMake setting to make it this way). My dev machine, it is located under: ${CMAKE_SOURCE_DIR}/build/test/Debug/.

For this reason, simply run test-orc where it is located will failed because the test cannot find examples dir (Of course, we can just copy test-orc to the appropriate dir but doing so every time is kinda annoying).

For this reason, I suggest to use the absolute path instead of a relative one.

**Comment by omalley** [comment]
When I run it manually, I run it as "test/test-orc" from the build directory. Since the build directory is one level down, "../examples/" works. Please make the runtime default the absolute path, but remove the CMake switch.

**Comment by thanhdowisc** [comment]
I'll revert to the original, but will make changes so that TestDriver can handle the case where argc >= 2
