### ISSUE TITLE
file-statistics aborts if there are no stripe statistics

### ISSUE THREAD

**Issue by swalkaus** [hortonworks/orc#142]
Here's the tail of output, running file-statistics, on a hive-11 file which appears not to have any stripe-level stats:

*** Column 20 ***
Data type: Integer
Values: 133607834
Minimum: 705050730
Maximum: 806202336
Sum: 94209489537413466

File /mnt/qa-scratch01/orc_data/perf/hive11_zlib/orderupc_bigfile/000000_0 has 14 stripes
terminate called after throwing an instance of 'std::logic_error'
  what():  stripe index out of range
Aborted (core dumped)

**Comment by jxu1989** [comment]
Will stripes all have or all not have statistics? Or is it possible some stripes have statistics and some don't have? 

If it is the first case, we can add a flag or add getNumOfStripeStatistics() in Reader. It would be 0 or numberOfStripes.

**Comment by omalley** [comment]
Either it won't have stripe statistics or it won't. I don't think you should have a case where only some of the stripes will have statistics.

**Comment by jxu1989** [comment]
yes, otherwise, it won't make sense to use stripeIndex to get statistics and won't know the ith stripestatistics in metadata is actually for which stripe.
