### ISSUE TITLE
Merge recent changes in c++ to c++09

### ISSUE THREAD

**Issue by thanhdowisc** [hortonworks/orc#143]
At Microsoft, we plan to build some prototype that uses the library and we would like to get the latest features and tests. Unfortunately, c++09 seems to lack pretty far behind c++. Could someone merge all recent changes in c++ to c++09?

**Comment by asandryh** [comment]
Fixed with commit c1364e609a

**Comment by thanhdowisc** [comment]
Windows build is broken with this merge.

**Comment by thanhdowisc** [comment]
Thanks for merging.
