### ISSUE TITLE
Merge recent changes to c++09

### ISSUE THREAD

**Issue by thanhdowisc** [hortonworks/orc#181]

**Comment by omalley** [comment]
What are you trying to accomplish? c++09 is a dead branch and has been for three months. When we move over to Apache, we'll move over the c++ branch.

**Comment by thanhdowisc** [comment]
Yes, I understand that nobody has merge changes from c++ to c++09 for more than 3 months.

I want the latest snapshot of native ORC that can compile in VC 2010, which does not support many C++11 features. For this reason, the current c++ branch does not compile in VC 2010.

Could you please let me know the timeline of moving to Apache? And do we plan to support VC 2010 in Apache release?

**Comment by thanhdowisc** [comment]
Before moving to Apache, I want to make sure there is no breaking for Windows in c++ branch (I will have to use VC2013 though). What do you think, Owen?

**Comment by asandryh** [comment]
You can build 'c++' branch without C++11 support, look at the build instructions.

**Comment by omalley** [comment]
Unfortunately, we are waiting for the HP & Hortonworks legal departments to make a formal code grant to Apache, so the timing isn't clear. Clearly we need a version of the code that works on windows and if that is some branch other than c++, we can copy that too. 

That said, it would be great to get the c++ branch working on windows.

**Comment by thanhdowisc** [comment]
Great! I am working on making c++ branch working in Windows.
