### ISSUE TITLE
Refactor the C09Adaptor magic

### ISSUE THREAD

**Issue by omalley** [hortonworks/orc#198]
After seeing @thanhdowisc 's work on making ORC work on Windows, it is pretty clear to me that we need to step back and need to stop using the compiler name & version and instead focus on whether individual features are available.

Cmake has a set of C++ feature tests that are already available, so I'd like to use those to drive the adaptor to the system where we can and add CHECK_CXX_SOURCE_COMPILES where there isn't a compiler feature already.

**Comment by thanhdowisc** [comment]
+1

**Comment by asandryh** [comment]
Sounds good. C09Adapter has always been a bit of a hack.

**Comment by omalley** [comment]
*sigh* Unfortunately, I just discovered that the cool stuff that I found last night is only available in cmake 3.1. So, the question become do we require a higher version of cmake or write more of the tests ourselves. Here is the cmake default version matrix:

OS | Cmake version
----- | -------------------
CentOS 7 | 2.8
CentOS 6 | 2.8
CentOS 5 | 2.6
MacPorts 2.3 | 3.2
Ubuntu 14 | 2.8

Cmake version | Release Date
-------------------- | -------------------
2.6 | May 2008
2.8 | Nov 2009
3.1 | Dec 2014
3.2 | Mar 2015

Currently we require cmake 2.6 and based on the tables above, we can't reasonably assume cmake > 2.8 without assuming that everyone will need to install it. My inclination at this point is to leave the requirement at 2.6 unless there is a compelling need to move to 2.8.

Thoughts?

**Comment by asandryh** [comment]
CMake 3.1 is too recent and probably won't be a default version on most Linux OS for years. From my recent experience, using a custom CMake version to build the orc library is a non-trivial task, especially if it is installed alongside the default cmake.
I suggest we keep this issue open, and revisit it in the future. The CMake features that you mentioned are too good to simply pass by. :)
