### ISSUE TITLE
Evaluate definitions and use of buffers

### ISSUE THREAD

**Issue by asandryh** [hortonworks/orc#200]
We need buffers that 
- are lightweight
- require as little copying between buffers as possible
- are compatible with asio API
- can be allocated from a custom memory pool

**Comment by omalley** [comment]
Actually, Aliaksei, let's move this discussion over to Orc's Apache Jira. 

https://issues.apache.org/jira/browse/orc

**Comment by omalley** [comment]
Moved to Apache as ORC-5.
