### ISSUE TITLE
Dual license as (Boost OR Apache-2.0)

### ISSUE THREAD

**Issue by Downchuck** [hortonworks/orc#204]
Dual license under Boost and Apache 2.0 would allow this C++ project to be used in environments where the more liberal Boost license is widespread.

**Comment by omalley** [comment]
We're in the process of moving to Apache where dual licensing would be difficult.

**Comment by Downchuck** [comment]
Makes sense: what are the means for starting that dialog? ORC encoding has exceptionally wide applicability. Simply, zip+csv to orc is a tremendous difference in storage and accessibility of data sets.

**Comment by omalley** [comment]
Apache doesn't have any infrastructure to make sure that all of the contributions satisfy any license but Apache.

What is it that you want to accomplish that can't be done with the Apache license? The Apache license is relatively liberal.

**Comment by Downchuck** [comment]
Compilation into projects that do not currently have attribution clauses
for binary distributions.

**Comment by omalley** [comment]
This unfortunately would require the permission from Hortonworks, HP, and Microsoft legal departments. Given the difficulty that I've had just trying to get them to formally agree to moving it to Apache, I don't think this will ever happen.

**Comment by Downchuck** [comment]
Appreciated, I'll take that effort in a different direction. This is a fantastic project and I'm glad to see it under the Apache umbrella.
