### ISSUE TITLE
Add ability to serialize the file footer and use that instead of re-reading file

### ISSUE THREAD

**Issue by omalley** [hortonworks/orc#209]
In Hadoop we often need to read the same file from multiple processes. Thus, the ability to read the file footer once and then read the rows on a remote server without having to re-read the file footer is useful.

In a related change, it would be better to make the stripe statistics load lazily instead of forcing every reader to load them.

**Comment by asandryh** [comment]
+1.
I made a comment about a protobuf header file in Reader.cc - please take a look.
