### ISSUE TITLE
Replace c++ streams in FIleInputStream with open/pread/close

### ISSUE THREAD

**Issue by omalley** [hortonworks/orc#44]
Profiling shows that the C++ streams are really slow for the primary data path.

**Comment by thanhdowisc** [comment]
Hi Owen!

This change will break windows build, since there pread is posix specific. Perhaps we should add some ifdef to address cross platform issues. Although a cleaner approach is needed though. 

I'll attempt to address this in a pull request that make c++09 build successfully in AppVeyor

**Comment by omalley** [comment]
@thanhdowisc please open a new issue for replacing pread with seek/read.
