### ISSUE TITLE
Change API to use size specific types

### ISSUE THREAD

**Issue by omalley** [hortonworks/orc#49]
In particular, we need to use int64_t and uint64_t for the relevant parts of the api. We should also use size_t and off_t in the appropriate spots.

**Comment by omalley** [comment]
I'll take this one.

**Comment by asandryh** [comment]
Wait! :) I have already resolved this on 'vertica2main' branch and will create a pull request today.

**Comment by asandryh** [comment]
Ah, I didn't reference the issue in my commit; that's why it isn't here

**Comment by asandryh** [comment]
commit 08d77a7c8e800774f6203690df8c755088de646c
