### ISSUE TITLE
Setting up CI for windows VC10

### ISSUE THREAD

**Issue by thanhdowisc** [hortonworks/orc#70]

**Comment by thanhdowisc** [comment]
Hi Owen,

Could you please let me know which branches I should generate the CI build? Should it be C++ or C++09 or both? VS10 is now broken on my dev machine due to some recent commits.

I guess the overall approach would be setting up a Windows CI for certain branches first, then fix the broken builds (I am sure the build will break).

Please let me know your thoughts.

Best,
Thanh

**Comment by omalley** [comment]
Thanh,
   I'd suggest that you set it up for c++ and c++09 for now.

**Comment by thanhdowisc** [comment]
Hi Owen,

One challenge I found with CI in Windows is that it cannot download and install dependencies automatically because there is no such thing like apt-install and yum. To build a dependency you would have download their zip file manually (again there is no wget in windows), and build it either from command line (if the zip file is configured to build on command line) or open a Visual Studio project to do so.

To workaround this issue, I may have to create a folder to store prebuilt libraries and headers of some dependencies (e.g, protobuf and zlib) and hack CMake find appropriate libraries in the folder. Does this sound good?

**Comment by omalley** [comment]
If you need libraries, you can put them in the lib directory. Everything you put in there has to be source code and not prebuilt libraries. Modify the CMake file in that directory to build the directories that you need on Windows. So if you need protobuf and zlib, put them in as lib/zlib-1.2.8 and lib/protobuf-2.6.0.

**Comment by thanhdowisc** [comment]
This sounds good. Once I am done with this on my dev machine, should I do a pull request against c++09? or it should be against c++?

**Comment by omalley** [comment]
c++ is the "trunk". However, in the next week we need to merge the c++09 branch into c++.

**Comment by asandryh** [comment]
I am currently working on merging the latest changes from c++ into c++09. It is painful... The sooner we make c++09 branch the trunk, the better.


On 01/28/2015 12:24 PM, omalley wrote:

c++ is the "trunk". However, in the next week we need to merge the c++09 branch into c++.
