### ISSUE TITLE
Fix the unit tests for int128 in TestInt128.cc.

### ISSUE THREAD

**Issue by asandryh** [hortonworks/orc#78]

**Comment by asandryh** [comment]
One of the tests for int128 data type breaks deterministically when I run 'make test'.

**Comment by omalley** [comment]
Yeah, I'm working on this. It only seems to fail on Ubuntu. It works on my Arch linux and Mac. I had to set up an ubuntu docker instance to get it to fail for me.

**Comment by omalley** [comment]
Ok, I found it. I was walking off the end of stack array. Not sure why valgrind didn't flag it for me. :)
