### ISSUE TITLE
Add snappy library to libs folder

### ISSUE THREAD

**Issue by thanhdowisc** [hortonworks/orc#86]

**Comment by thanhdowisc** [comment]
What snappy version should we use? 1.1.2?

**Comment by thanhdowisc** [comment]
A complication is that there is no cmake for snappy yet! I found a windows port here with BSD licences

https://bitbucket.org/robertvazan/snappy-visual-cpp/downloads

**Comment by omalley** [comment]
I added snappy-1.1.2 and created a cmake file for it.

**Comment by thanhdowisc** [comment]
Great! Thanks! I was working on a separate branch to enable snappy in windows but with this checked in, that branch is no longer needed.

Btw, could you merge recent changes to c++09? And for apache release, do we plan to support c++09 in the long run?
