### ISSUE TITLE
Add option not to use snappy compression.

### ISSUE THREAD

**Issue by thanhdowisc** [hortonworks/orc#89]
Mac and Linux currently use snappy from the systems, where windows will have to rely on the library from libs directory. 

The problem is that (as far as I know) there is no cross-platform src repo for snappy. Adding a windows-specific version of snappy (e.g., from here http://snappy.angeloflogic.com/) does not make much sense since the overall plan is to have all platforms using the libraries from libs.

Thus, this option will allow build with snappy disabled in Windows to success.

Any thoughts?

**Comment by omalley** [comment]
For anything other than a short term work around, this is not a good option. Lots of ORC files have snappy compression and it should be supported.

What did Hadoop on Windows do for Snappy?

Don't add a switch that turns off snappy, if you need to disable snappy on Windows, use Windows as the trigger.

**Comment by thanhdowisc** [comment]
Hi Owen. 

I didn't mean to not to support snappy. This is is just a short term work around in order to get at least the c++09 branch build successfully on Windows at the moment. Currently the branch broke because of Windows cannot do a ''apt-install snappy'' automatically. 

Hadoop on Windows uses a Java version of snappy and there is a binary jar file included in the distribution.

Our goal the moment is to get at least the branch c++09 build successfully. To obtain this short-term goal, I have thought of a couple of options.

1. pass a flag to cmake and use this to guide the compiler to skip over snappy code.
2. add snappy src in libs, and change cmake file so that if the platform is Windows, then use snappy from libs folder. Otherwise, use snappy from the systems.
3. use ifdef to skip over snappy code in Windows.

Option 1 is not the ideal choice, because as you said, it would give an option to disable snappy in all platform.

Option 2 enables what we eventually need: snappy code in Windows, but implementing it may violate another goal to make all platforms use libraries from the libs folder (#80). In the long term, I think we should add cmake support to native snappy and put snappy in libs.

Option 3 is quick, simple, and windows specific. It does not affect other platform.

I think option 3 is good candidate for a quick fix for now. What do you think?

**Comment by omalley** [comment]
yeah, i think option 3 is the best for right now.
